import { Tour, Booking, User } from './types';

export const mockTours: Tour[] = [
  {
    id: '1',
    title: 'Bali Paradise Explorer',
    description: 'Experience the magic of Bali with visits to ancient temples, pristine beaches, and vibrant rice terraces.',
    destination: 'Bali, Indonesia',
    duration: 7,
    price: 1299,
    maxParticipants: 20,
    currentParticipants: 15,
    image: 'https://images.unsplash.com/photo-1537225228614-20dd305803f0?w=500&h=400&fit=crop',
    startDate: '2024-08-15',
    endDate: '2024-08-22',
    highlights: ['Ubud Temple', 'Mount Batur Sunrise', 'Tegallalang Rice Terraces', 'Seminyak Beach'],
    inclusions: ['4-star hotel', 'All meals', 'Guide', 'Entrance fees'],
    difficulty: 'easy',
    rating: 4.8,
    reviews: 342,
  },
  {
    id: '2',
    title: 'Swiss Alpine Adventure',
    description: 'Explore the stunning Swiss Alps with guided hiking, mountain villages, and breathtaking scenery.',
    destination: 'Switzerland',
    duration: 10,
    price: 2499,
    maxParticipants: 15,
    currentParticipants: 12,
    image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=500&h=400&fit=crop',
    startDate: '2024-09-01',
    endDate: '2024-09-11',
    highlights: ['Jungfrau Peak', 'Interlaken', 'Grindelwald', 'Lauterbrunnen Valley'],
    inclusions: ['5-star hotel', 'Breakfast & dinner', 'Professional guide', 'Cable car passes'],
    difficulty: 'moderate',
    rating: 4.9,
    reviews: 287,
  },
  {
    id: '3',
    title: 'Machu Picchu Expedition',
    description: 'Trek to the Lost City of Incas with experienced guides and immerse in Peruvian culture.',
    destination: 'Peru',
    duration: 8,
    price: 1899,
    maxParticipants: 12,
    currentParticipants: 8,
    image: 'https://images.unsplash.com/photo-1587595431973-160ef0d6470a?w=500&h=400&fit=crop',
    startDate: '2024-08-20',
    endDate: '2024-08-28',
    highlights: ['Inca Trail Trek', 'Machu Picchu', 'Sacred Valley', 'Cusco City Tour'],
    inclusions: ['3-4 star accommodations', 'Meals included', 'Expert guides', 'Trek permits'],
    difficulty: 'hard',
    rating: 4.7,
    reviews: 415,
  },
  {
    id: '4',
    title: 'Egypt Nile Cruise',
    description: 'Discover ancient Egypt with a luxurious Nile cruise and guided historical tours.',
    destination: 'Egypt',
    duration: 9,
    price: 1699,
    maxParticipants: 30,
    currentParticipants: 24,
    image: 'https://images.unsplash.com/photo-1504681869696-d977e0b67cf4?w=500&h=400&fit=crop',
    startDate: '2024-10-10',
    endDate: '2024-10-19',
    highlights: ['Pyramids of Giza', 'Valley of Kings', 'Luxor Temple', 'Aswan & Philae Temple'],
    inclusions: ['5-star Nile cruise', 'All meals', 'Experienced Egyptologist guide', 'Entrance fees'],
    difficulty: 'easy',
    rating: 4.6,
    reviews: 523,
  },
  {
    id: '5',
    title: 'Iceland Glacier & Waterfall Tour',
    description: 'Experience Iceland\'s dramatic landscapes with glacier hiking, waterfalls, and geothermal hot springs.',
    destination: 'Iceland',
    duration: 6,
    price: 1599,
    maxParticipants: 16,
    currentParticipants: 10,
    image: 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?w=500&h=400&fit=crop',
    startDate: '2024-07-15',
    endDate: '2024-07-21',
    highlights: ['Vatnajökull Glacier', 'Skógafoss Waterfall', 'Blue Lagoon', 'Golden Circle'],
    inclusions: ['4-star hotel', 'Breakfast included', 'All activities', 'Professional guide'],
    difficulty: 'moderate',
    rating: 4.9,
    reviews: 298,
  },
];

export const mockBookings: Booking[] = [
  {
    id: 'b1',
    tourId: '1',
    userId: 'u1',
    participants: 2,
    totalPrice: 2598,
    bookingDate: '2024-07-01',
    status: 'confirmed',
    customerName: 'John Doe',
    customerEmail: 'john@example.com',
    customerPhone: '+1-555-0101',
  },
];

export const mockUsers: User[] = [
  {
    id: 'u1',
    name: 'John Doe',
    email: 'john@example.com',
    phone: '+1-555-0101',
    bookings: ['b1'],
  },
];
